### ISSUE TITLE
False positives with cached queries 

### ISSUE THREAD

**Issue by andrewr224** [PigCI/pig-ci-rails#26]
It would be useful if cached queries were ignored, or at least if there was an option to ignore them

**Comment by MikeRogers0** [comment]
@andrewr224 I can totally see how that would throw off the usefulness!

I think it should be possible, could you give me a quick code sample of how you've setup cached queries so I can experiment?

**Comment by andrewr224** [comment]
@MikeRogers0, the simplest example I encountered is conditionally decorating `current_user`.

Gems in use are [devise](https://github.com/heartcombo/devise), [draper](https://github.com/drapergem/draper), and [rolify](https://github.com/RolifyCommunity/rolify).

In my `application_controller` I have 
```
  def current_user
    super&.decorate
  end
```

And, as I wanna decorate users with different decorators, in my `user_model` I have
```
  def decorate(**)
    return TenantDecorator.new(self)   if tenant?
    return LandlordDecorator.new(self) if landlord?

    super
  end

  def tenant?
    has_role? :tenant # => automatically cached by rolify
  end

  def landlord?
    has_role? :landlord # => automatically cached by rolify
  end
```

I'll provide other examples if need be.

**Comment by MikeRogers0** [comment]
@andrewr224 Thank you for the example, I'll get looking into options :)

In the interim, have you considered an approach like:

```
  def current_user
    @current_user ||= super&.decorate
  end
```
 That should stop you even needing the look at the cache SQL queries :)

**Comment by MikeRogers0** [comment]
Good news @andrewr224 https://github.com/PigCI/pig-ci-rails/pull/33 - I merged an update to solve this into `master` :D

Could you to update your gemfile to be:

```
gem 'pig-ci-rails', github: 'PigCI/pig-ci-rails', branch: 'master'
```

Then update one of your tests to confirm for me it's a good solution? Thanks!

**Comment by MikeRogers0** [comment]
Closing this off - It looks ok to me.

**Comment by andrewr224** [comment]
@MikeRogers0 , yes, that fixed it. Thanks
