### ISSUE TITLE
Rails 4 support?

### ISSUE THREAD

**Issue by paniko0** [PigCI/pig-ci-rails#29]
Hi,

I've been trying to sue this gem in a Rails 4 project but found a problem on the eager loading part.

Essentially https://github.com/PigCI/pig-ci-rails/blob/master/lib/pig_ci/profiler_engine/rails.rb#L40 tries to run `.eager_load!`, however, as per my understanding, this method was only included on Rails 5 here https://github.com/rails/rails/pull/27647

It raises the following error

```
Failure/Error: PigCI.start

NoMethodError:
  undefined method `eager_load!' for #<ActionDispatch::Routing::RouteSet:0x00007fcf1a82a820>
# /Users/dsouza/.rvm/gems/ruby-2.6.3/gems/pig-ci-rails-1.0.0/lib/pig_ci/profiler_engine/rails.rb:40:in `eager_load_rails!'
# /Users/dsouza/.rvm/gems/ruby-2.6.3/gems/pig-ci-rails-1.0.0/lib/pig_ci/profiler_engine/rails.rb:24:in `block in setup!'
# /Users/dsouza/.rvm/gems/ruby-2.6.3/gems/pig-ci-rails-1.0.0/lib/pig_ci/profiler_engine.rb:25:in `setup!'
# /Users/dsouza/.rvm/gems/ruby-2.6.3/gems/pig-ci-rails-1.0.0/lib/pig_ci/profiler_engine/rails.rb:22:in `setup!'
# /Users/dsouza/.rvm/gems/ruby-2.6.3/gems/pig-ci-rails-1.0.0/lib/pig_ci.rb:133:in `start'
```

Am I missing something here? I commented the `eager_load!` piece and everything seemed to work fine. I am opened to create a PR if supporting Rails 4 is something that you intended with this gem.

Thanks!

**Comment by MikeRogers0** [comment]
Thank you for reporting this! I had only tested it down to Rails 5.2. 

For now you can work around this issue by updating the `PigCI.start` reference to include `during_setup_eager_load_application = false`.

```ruby
PigCI.start do |config|
  config.during_setup_eager_load_application = false
end
```

**Comment by paniko0** [comment]
Is it something worth fixing? Otherwise I think we can close this issue.

Cheers

**Comment by MikeRogers0** [comment]
@paniko0 I think it's worth me fixing :) I'm aiming to get on it the next time I have a free weekend.

**Comment by paniko0** [comment]
I can take a look as well if you wish. Just need to know what would be the intended behaviour on Rails 4.

**Comment by MikeRogers0** [comment]
Bugfix was merged, closing this off now :)
