### ISSUE TITLE
Ignore specific specs?

### ISSUE THREAD

**Issue by ffmike** [PigCI/pig-ci-rails#30]
This is definitely a feature request, not a bug. 

My specs have a "long tail" where a couple of PDF-generation methods take way longer than anything else to run. If I set the threshold long enough that they don't get flagged, then even a 100% increase in one of the regular UI calls won't trigger a PigCI failure.

I'm envisioning some way to decorate particular specs to be ignored, similar to the magic comments that can hide code from SimpleCov or RuboCop.

**Comment by MikeRogers0** [comment]
Hi @ffmike ! This seems like a super feature request!

I was thinking of hooking into the RSpec metadata options (something like `it "Test Description", pig_ci: false` do). I'll have experiment this afternoon to see what I can get together :)

**Comment by MikeRogers0** [comment]
@ffmike - I've just pushed an update to master, are you able to update your gemfile to be:

```
gem 'pig-ci-rails', github: 'PigCI/pig-ci-rails', branch: 'master'
```

Then update one of your tests to include the metadata `pig_ci: false` & confirm for me it's a good solution? Thanks!

**Comment by ffmike** [comment]
Works perfectly. Tested on response time and query count, at both the spec & context level. Thanks!

**Comment by MikeRogers0** [comment]
Awesome!!!! Thank you so much @ffmike !
